modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/team-abnormals/${archives_base_name}/issues"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "Team Abnormals"
credits = "SmellyModder, bageldotjpg, Jackson"
logoFile = "logo.png"
itemIcon = "minecraft:creeper_head"
configBackground = "blueprint:textures/blueprint.png"
displayURL = "${homepage}"
description = "${mod_description}"
#logoFile = ""

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}-common.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"